### ISSUE TITLE
build application fail on windows

### ISSUE THREAD

**Issue by liuaifu** [boostorg/python#195] opened 2018-04-18 07:43 UTC
Today, i download boost1.67 release replace 1.66 on windows 7 & vs2017, compile it, get:
boost_python36-vc141-mt-gd-x32-1_67.dll
boost_python36-vc141-mt-gd-x32-1_67.lib
libboost_python36-vc141-mt-gd-x32-1_67.lib
and other libraries.
But build my own app fail:

    LNK1104	can't open file boost_pythonPY_MAJOR_VERSIONPY_MINOR_VERSION-vc141-mt-gd-x32-1_67.lib

The app is build corrent on boost1.66.

**Comment by stefanseefeld** [comment] 2018-04-19 01:32
This is a duplicate of https://github.com/boostorg/python/issues/193.

**Closed by stefanseefeld** 2018-04-19 01:32 UTC
