### ISSUE TITLE
make_unqiue 

### ISSUE THREAD

**Issue by Ira0134** [boostorg/python#86] opened 2016-09-01 03:08 UTC
acording to this  http://stackoverflow.com/questions/20581679/boost-python-how-to-expose-stdunique-ptr
i think many people need make_unqie for boost::python
Boost.Python's news/change log has no indication that it has been updated for C++11 move-semantics
Additionally, this feature request for unique_ptr support has not been touched for over a year.

We need unqiue_ptr and make unqiue_support as you can see in tht topic on staackoverfow is already a solution.
Thanks

**Comment by stefanseefeld** [comment] 2016-09-01 04:07
This is a duplicate of https://github.com/boostorg/python/issues/80. Please follow up there.

**Closed by stefanseefeld** 2016-09-01 04:07 UTC
