### ISSUE TITLE
integrate support of std::shared_ptr in addition to boost::shared_ptr and perhaps other smart pointers implementing similar concepts

### ISSUE THREAD

**Issue by nevion** [boostorg/python#29] opened 2015-07-27 05:13 UTC
currently the support of boost::shared_ptr islands code using std::shared_ptr.  While in some cases the user can simply choose to use boost::shared_ptr over std::shared_ptr, this does not work on a pre-existing library whom chose to use std::shared_ptr.

It may also be worth considering older libraries out there who'm had chosen to implement their own smart ptr ( e.g. OpenSceneGraph, ITK/VTK) though I'm not sure they'll support 1:1 the same exact concepts shared_ptr does.

**Comment by mad0house** [comment] 2015-09-01 09:54
Could do with this.

**Comment by bhack** [comment] 2015-09-19 10:31
:+1:

**Comment by eudoxos** [comment] 2015-09-27 09:41
This is the original ticket: https://svn.boost.org/trac/boost/ticket/6545 and the missing functionality with std::shared_ptr (no implciit upcasting) was discussed at c++-sig http://thread.gmane.org/gmane.comp.python.c++/15759/focus=15771 .

**Comment by KayEss** [comment] 2015-12-19 04:02
Did something change here between 1.59 and 1.60? I'm just testing the new version and we're getting testing errors now with things like:

    TypeError: No to_python (by-value) converter found for C++ type: std::shared_ptr<fostlib::jsondb::local>

We have recently changed these from using boost::shared_ptr to std::shared_ptr, but everything works in Boost 1.56 to 1.59 but it fails now with 1.60. The wrapper is [here](https://github.com/KayEss/fost-py/blob/master/Cpp/fost-json-py/json-py.cpp#L40).

I saw the post linked above, but have no idea where to put that. I don't think this is affected anyway as there is no class hierarchy involved.

**Comment by stefanseefeld** [comment] 2015-12-19 04:11
I'm not aware of any related changes in Boost.Python. In particular, I don't think std::shared_ptr was ever supported in Boost.Python (I do want to add support for this, but haven't had the time to set up builds with a C++11 compatible compiler to test this.)

**Comment by KayEss** [comment] 2015-12-19 04:17
Thanks. Sounds like I ought to convert all of the std::shared_ptr to boost::shared_ptr though anyway. Hopefully that will work.

**Comment by ycollet** [comment] 2016-01-07 10:18
The same for me here.
Our application works fine with boost-1.59 and fails with boost-1.60 with problems related to shared_ptr.

**Comment by KayEss** [comment] 2016-01-08 05:10
@ycollet What are the actual errors that you see? Are you seeing the same sort of errors we are? We're getting problems in the type registry:

    TypeError: No to_python (by-value) converter found for C++ type: boost::shared_ptr<fostlib::jsondb::local>

I've switched between `std::shared_ptr` and `boost::shared_ptr` and it doesn't make any difference. I wonder what changes were made to `shared_ptr` between 1.59 and 1.60....

**Comment by ycollet** [comment] 2016-01-08 07:24
I've got the same error message as you:

TypeError: No to_python (by-value) converter found for C++ type: boost::shared_ptr<*>

----- Mail original -----
De: "Kirit Sælensminde" <notifications@github.com>
À: "boostorg/python" <python@noreply.github.com>
Cc: "ycollet" <ycollette.nospam@free.fr>
Envoyé: Vendredi 8 Janvier 2016 06:10:53
Objet: Re: [python] integrate support of std::shared_ptr in addition to boost::shared_ptr and perhaps other smart pointers implementing similar concepts (#29)



@ycollet What are the actual errors that you see? Are you seeing the same sort of errors we are? We're getting problems in the type registry: TypeError: No to_python (by-value) converter found for C++ type: boost::shared_ptr<fostlib::jsondb::local> 

I've switched between std::shared_ptr and boost::shared_ptr and it doesn't make any difference. I wonder what changes were made to shared_ptr between 1.59 and 1.60....

**Comment by KayEss** [comment] 2016-01-08 07:34
There's nothing in the release notes about changes to either the python or pointer libraries. I think it's fair to say that if we're both getting the same sort of problem it's less likely that we're both doing the same stupid thing that triggers it.

I've been meaning to set up a build mechanism that would allow me to build against the current development version of Boost. If I can do that then bisecting between 1.59 and 1.60 might find the problem.

BTW, I'm doing C++14 builds and get the same problem on both gcc and clang.

**Comment by ycollet** [comment] 2016-01-08 08:17
I fear that this problem comes from a change from a change on another lib. 
I had a look at the changes between 1.59 and 1.60 and nothing really evident shows up.

**Comment by stefanseefeld** [comment] 2016-01-08 12:39
Thanks for investigating this ! 
Just FYI, I'm experimenting with ways to build Boost.Python stand-alone (using something other than Boost.Build), to make it easier to maintain and perhaps even develop. Right now I'm still stuck with Boost.Build, and I have a hard time doing anything with it, including trying to change compiler flags (such as adding --std=c++11) so I can experiment with adding support for std::shared_ptr.

**Comment by KayEss** [comment] 2016-01-11 04:22
@stefanseefeld This may help you: https://github.com/KayEss/fost-py/blob/master/Cpp/fost-json-py/Jamfile

The `$TARGET_REQUIREMENTS` are defined in https://github.com/KayEss/fost-base/blob/master/fost.jam#L37 You'll notice it includes C++14 flags.

It is also possible to pass in compiler flags to the bjam command line, but I forget how to do that :) It is nearly impossible to find this stuff in the docs :(

**Comment by finjulhich** [comment] 2016-01-11 12:05
you can ask on the boost or boost-build mailing list, from experience,
Vladimir answers promptly.

**Comment by jhunold** [comment] 2016-01-11 12:40
See http://www.boost.org/build/doc/html/bbv2/overview/builtins/features.html for the "cxxflags" feature.
Or just grep the Jamfiles in the Boost sources for "-std=" to find existing examples.

**Comment by bennybp** [comment] 2016-02-04 01:53
I'm also experiencing the error with boost::shared_ptr referenced by @KayEss and @ycollet. I managed to bisect with a simple test program and script. It appears to come from an update/rewrite of type_traits around commit f0da159e1f52e87ad71e4747de6b042c54578e0e (in the type_traits submodule, although that commit won't compile for me).

Unfortunately, it looks like a big rewrite in one commit, so I don't know the exact cause, but I hope this helps

**Comment by KayEss** [comment] 2016-02-04 03:36
Well found @bennybp [Here's a link to the commit.](https://github.com/boostorg/type_traits/commit/f0da159e1f52e87ad71e4747de6b042c54578e0e) Not really surprised there was a regression in it given how large it is.

**Comment by epot** [comment] 2016-02-05 16:21
Concerning the boost regression between 1.59 and 1.60, I had a similar one ad I created a post on stackoverflow about it:
http://stackoverflow.com/questions/35056398/typeerror-when-iterating-over-a-boostpython-vector

If we do have the same issue, it is completely unrelated to smart pointers.

**Comment by kilojoules** [comment] 2016-02-09 20:51
I'm getting a "did not match C++ signature" error. 
I found this SO question
[https://stackoverflow.com/questions/20825662/boost-python-argument-types-did-not-match-c-signature](https://stackoverflow.com/questions/20825662/boost-python-argument-types-did-not-match-c-signature)
which led me to this issue. Here is the error I'm facing:

    pyDAKOTA.run_dakota_mpi(TestDriver, Communicator, NoneType, NoneType, _ExcInfo)
did not match C++ signature:
    run_dakota_mpi(char*, boost::mpi::communicator {lvalue}, char*, char*, boost::python::api::object)

**Comment by eudoxos** [comment] 2016-02-10 08:58
Just as a reminder, the problem with missing converter which arose between 1.59 and 1.60 is, as far as I see, orthogonal to this issue (though certainly valid) -- which is to support std::shared_ptr (and perhaps other smart pointer types) at the same level as boost::shared_ptr (including e.g. automatic upcasting).

**Comment by epot** [comment] 2016-02-10 09:00
I definitely agree: I have this issue without any smart pointer.

**Comment by wojdyr** [comment] 2016-02-11 13:33
@eudoxos @epot yes, so I just opened a separate issue for the regression

**Comment by stefanseefeld** [comment] 2016-09-27 18:41
I have just merged support for `std::shared_ptr` into the `develop` branch (https://github.com/boostorg/python/commit/97e4b34a15978ca9d7c296da2de89b78bba4e0d5), so whenever Boost.Python is compiled with a C++11-compliant compiler std::shared_ptr is supported in exactly the same way as `boost::shared_ptr`. I plan to add some documentation (in particular release notes), then prepare for this to be merged into master for the next (i.e., 1.63) release.

**Closed** 2016-09-29 11:44 UTC
Labels: C++-11

**Comment by NOhs** [comment] 2016-11-09 12:17
I can't find this feature in the notes for the 1.63 release [svn-milestone-1.63-link](https://svn.boost.org/trac/boost/query?group=status&milestone=Boost+1.63.0). Is it just not in that list, or will it be delayed?

**Comment by stefanseefeld** [comment] 2016-11-09 12:48
It will be part of 1.63. See http://www.boost.org/users/history/version_1_63_0.html for tentative release notes. (I doubt trac will reflect current efforts, as more and more projects move over to github issue tracking.)

**Comment by NOhs** [comment] 2016-11-09 15:34
Nice. Looking forward to it!
